# Generated by Django 4.0 on 2022-02-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
