# Generated by Django 4.0 on 2022-02-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_courses_duration'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addmission', to='course.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addmission', to='student.student')),
            ],
        ),
    ]
